[[subsets]]
num_repeats = 1
keep_tokens = 0
caption_extension = ".txt"
shuffle_caption = false
flip_aug = false
color_aug = false
random_crop = false
is_reg = false
image_dir = ""

[noise_args]

[sample_args]

[logging_args]

[general_args.args]
pretrained_model_name_or_path = ""
mixed_precision = "fp16"
seed = 23
clip_skip = 2
xformers = true
max_train_epochs = 1
max_data_loader_n_workers = 1
persistent_data_loader_workers = true
max_token_length = 225
prior_loss_weight = 1.0

[general_args.dataset_args]
resolution = 512
batch_size = 1

[network_args.args]
network_dim = 32
network_alpha = 16.0

[optimizer_args.args]
optimizer_type = "AdamW"
lr_scheduler = "cosine"
learning_rate = 0.0001

[saving_args.args]
output_dir = ""
save_precision = "fp16"
save_model_as = "safetensors"

[bucket_args.dataset_args]
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64

[optimizer_args.args.optimizer_args]
weight_decay = 0.1
betas = "0.9,0.99"
